apiVersion: v1
kind: Service
metadata:
  labels:
    service: gitlab
  name: gitlab
  namespace: gitlab
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    nodePort: 30623
  selector:
    service: gitlab
status:
  loadBalancer: {}
